language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="4d28858a-fb26-40c0-ac74-f21010c4b0ca"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      aleksandr.litvinov89qw@gmail.com
    on_success: never # default: change
    on_failure: always # default: always